spring:
  # 数据源
  datasource:
    type: mysql
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://Altacloud-mysql:3306/altacloud??useUnicode=true&characterEncoding=UTF-8&useSSL=false
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  storage:
    type: mysql
sleuth:
  enabled: true
