server:
  port: 5002

spring:
  profiles:
    active: dev
  application:
    name: "@pom.artifactId@"

  security:
    basic:
      enabled: true
    user:
      name: root
      password: root

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://Altacloud-mysql:3306/altacloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
